classDiagram
    %% --------------------------------
    %% Cards
    %% --------------------------------
    Deck~T~ o-- Card
    class Card {
        <<abstract>>
        - ID: int
        - TYPE: CardType
        + Card (id: int, type: CardType)
        + getId() int
        + getType() CardType
        + getScoringCondition() Condition
        + getPlacementCondition() Condition
        + getScore() int
    }
    class GoldCard {
        - PLACEMENTCONDITION: Condition
        - SCORINGCONDITION: Condition
        + GoldCard(cardID: int, cardType: CardType,\n frontCorners: boolean[4], \nfrontCornersContent: GameItem[4], placementScore: int, \n permanentResources: List~GameResource~, \nplacementCondition: Condition, \nscoringCondition: Condition)
    }
    class NonStarterCard {
        - PLACEMENTSCORE: int
        + NonStarterCard(cardID: int, \ncardType: CardType, frontCorners: boolean [4],\n frontCornersContent: GameItem [4],\n placementScore: int,\n permanentResources: List~GameResource~)
    }
    class ObjectiveCard {
        - SCORINGCONDITION: Condition
        - OBJECTIVESCORE: int
        + ObjectiveCard(cardID int, cardType: CardType,\n scoringCondition: Condition, objectiveScore: int)
    }
    class PlaceableCard {
        <<abstract>>
        - PERMANENTRESOURCES: List~GameResource~
        - FRONTCORNERS: boolean [4]
        - FRONTCORNERSCONTENT: GameItem [4]
        + PlaceableCard (cardID: int, cardType: CardType,\n frontCorners: boolean [4], \n frontCornersContent: GameItem [4], \n permanentResources: List~GameResource~)
        + getFrontCorners() boolean [4]
        + getFrontCornersContent() GameItem[4]
        + getPermanentResources() GameResource[3]
        + getBackCorners() boolean [4]
        + getBackCornersContent() GameItem [4]
    }
    class StarterCard {
        - BACKCORNERS: boolean [4]
        - BACKCORNERSCONTENT: GameItem [4]
        + StarterCard(cardID: int, cardType: CardType, \n frontCorners: boolean [4], \nfrontCornersContent: GameItem [4],\n permanentResources: List~GameResource~, \nbackCorners: boolean[4], \nbackCornersContent: GameItem[4])
    }
    Card <|-- ObjectiveCard
    Card <|-- PlaceableCard
    PlaceableCard <|-- StarterCard
    PlaceableCard <|-- NonStarterCard
    NonStarterCard <|-- GoldCard
    %% --------------------------------
    %% Conditions
    %% --------------------------------
    class Condition {
        <<abstract>>
        - TYPE: ConditionType
        + Condition(type: ConditionType)
        + getType() ConditionType
        + numTimesMet(gameField: GameField) int
    }
    class CornerCoverageCondition {
        + CornerCoverageCondition(type: ConditionType)
    }
    class ItemsCondition {
        - NEEDEDITEMS: List~GameItem~
        + ItemsCondition(conditionType: ConditionType, \n neededItems: List~GameItem~)
        + getNeededItems() List~GameItem~
    }
    class LayoutCondition {
        - CARDSCOLOR: GameResource[3][3]
        - MAXLAYOUTROWS: int$
        - MAXLAYOUTCOLUMNS: int$
        + LayoutCondition(conditionType: ConditionType, cardsColor: GameResource[3][3])
        + getCardsColor() GameResource[3][3]
    }
    %%LayoutCondition --> GameResource
    %%ItemsCondition --> GameItem
    Condition <|-- LayoutCondition
    Condition <|-- ItemsCondition
    Condition <|-- CornerCoverageCondition
    %% --------------------------------
    %% Decks
    %% --------------------------------
    class Deck~T~{
        ~ TYPE: CardType
        ~ Stack~T~ content
        + Deck()
        + setType(type: CardType)
        + getType() CardType
        + drawCard() T
    }
    class PlayingDeck~T~{
        ~ faceUpCard: List~T~
        + PlayingDeck()
        + setFaceUpCards(faceUpCards: List~T~)
        + revealFaceUpCard(cardPos: int) T
    }
    class DrawableDeck~T~{
        + DrawableDeck()
        + drawFaceUpCard(cardPos: int) T
        ~ revealDeckCard() T
    }
    class GoldCardsDeck{
        + GoldCardsDeck()
        + revealBackDeckCard() GameResource
    }
    class ResourceCardsDeck{
        + ResourceCardsDeck()
        + revealBackDeckCard() GameResource
    }
    Deck~T~ <|-- PlayingDeck~T~
    PlayingDeck~T~ <|-- DrawableDeck~T~
    DrawableDeck~T~ <|-- ResourceCardsDeck
    DrawableDeck~T~ <|-- GoldCardsDeck

    %%Deck --> Card
    %% --------------------------------
    %% Enumerations
    %% --------------------------------
    class CardType {
        <<enumeration>>
        RESOURCE_CARD
        GOLD_CARD
        STARTER_CARD
        OBJECTIVE_CARD
    }
    class ConditionType {
        <<enumeration>>
        LAYOUT_CONDITION
        ITEM_CONDITION
        CORNER_COVERAGE_CONDITION
    }
    class GameObject {
        <<enumeration>>
        QUILL
        INKWELL
        MANUSCRIPT
    }
    class GameResource {
        <<enumeration>>
        PLANT
        ANIMAL
        FUNGI
        INSECT
    }
    class GameState{
        <<enumeration>>
        WAITING_PLAYERS
        PLAYING
        GAME_ENDED
    }
    class TokenColor {
        <<enumeration>>
        BLUE
        GREEN
        RED
        YELLOW
    }
    class GameItem {
        <<interface>>
    }
    GameItem <|.. GameResource
    GameItem <|.. GameObject

    class Chat {
        - messages: List~Message~
        + Chat()
        + addMessage(content: String, sender: String, isPublic: boolean,\n receiver: String, players: List~String~)
        + getContent(receiver: String) List~Message~
        + getLastMessage(receiver: String) Message
    }

    class Message{
        - CONTENT: String
        - SENDERNICKNAME: String
        - ISPUBLIC: boolean
        + Message(content: String, senderNickname: String, isPublic: boolean)
        + getContent() String
        + getSender() String
        + isPublic() boolean
        + getReceiver() String
    }

    class PrivateMessage{
        - RECEIVERNICKNAME: String
        + PrivateMessage(content: String, senderNickname: String, isPublic: boolean, receiverNickname: String)
    }

    Message <|-- PrivateMessage

    class Game {
        - state: GameState
        - playersNumber: int
        - playersGameField: Map~String, GameField~
        - players: List~Player~
        - currPlayer: int
        - scoreTrackBoard: ScoreTrackBoard
        - resourceCardsDeck: ResourceCardsDeck
        - goldCardsDeck: GoldCardsDeck
        - objectiveCardsDeck: PlayingDeck~ObjectiveCard~
        - starterCardsDeck: Deck~StarterCard~
        - twentyPointsReached: boolean
        - additionalRound : boolean
        - chat: Chat
        + Game(gameId: int, playersNumber: int, resourceCardsDeck: ResourceCardsDeck,\n goldCardsDeck: GoldCardsDeck, objectiveCardsDeck: PlayingDeck~ObjectiveCard~, starterCardsDeck : Deck~StarterCard~, \nnickname: String, tokenColor: TokenColor, connectionType: boolean,\n interfaceType :boolean, starterCardWay: boolean)
        + getState() GameState
        + getPlayers() List~Player~
        + getCurrentPlayer() Player
        + getGameField(nickname: String) GameField
        + getScore(nickname: String) int
        + addplayer(nickname: String, tokenColor: TokenColor, connectionType: boolean, interfaceType:  boolean, starterCardWay : boolean)
        + setup()
        + isFull() boolean
        + disconnectPlayer(nickname : String)
        + reconnectPlayer(nickname : String)
        + getPlayerByNickname(nickname : String) int
        + changeCurrPlayer()
        + placeCard(nickname: String, card: NonStarterCard, x:int, y:int, way:boolean)
        + addPoints(nickname: String, x: int, y:int)
        + computeWinner() List~Player~
        + drawDeckCard(nickname: String, type: CardType)
        + drawFaceUpCard(nickname: String, type : CardType, pos:int)
        + revealFaceUpCard(type: CardType, pos:int) Card
        + revealBackDeckCard(type: CardType) GameResource
        + addChatMessage(content: String, sender: String, isPublic: boolean, receiver: String)
        + getLastChatMessage(receiver: String) Message
        + getChatContent(receiver: String) List~Message~
    }
    %%  Game --> DrawableDeck
    %%  Game --> Deck
    %%  Game --> PlayingDeck
    %%  Game --> ScoreTrackBoard
    %%  Game --> Player
    %%  Game --> Chat
    %%  Game --> GameField
    class GameField {
        - DIM: int$
        - cardsContent: PlaceableCard[81][81]
        - cardsFace: boolean [81][81]
        - cardsOrder: int[81][81]
        - numPlayedCards: int
        + GameField()
        + GameField(GameField existingGameField)
        + getDim() int
        + placeCard(card: PlaceableCard, x: int, y: int, way: boolean)
        + isCardPresent(x: int, y: int) boolean
        + getPlacedCard(x: int, y: int) PlaceableCard
        + removePlacedcard(x: int, y: int)
        + getCardWay(x: int, y: int) boolean
        + getCardsOrder() int[81][81]
        + getNumPlayedCards() int
    }
    %%GameField --> PlaceableCard
    class GamesManager {
        - games: List~Game~
        + GamesManager()
        + addPlayer(nickname: String, tokenColor: TokenColor, connectionType: boolean, interfaceType: boolean, starterCardWay: boolean)
        + checkNickname(nickname: String) boolean
    }
    %%GamesManager --> Game
    class Player {
        - nickname: String
        - tokenColor: TokenColor
        - isFirst: boolean
        - connectionType: boolean
        - interfaceType: boolean
        - isConnected: boolean
        - currentHand: List ~NonStarterCard~
        - secretObjectve: ObjectiveCard
        + Player(nickname: String, tokenColor: TokenColor, connectionType: boolean,\n interfaceType: boolean, currentHand: List~NonStarterCard~, \nsecretObjective: ObjectiveCard)
        + Player(existingPlayer: Player)
        + getNickname() String
        + getTokenColor() TokenColor
        + setFirst()
        + isFirst() boolean
        + isConnected() boolean
        + setIsConnected(isConnected: boolean)
        + setCurrentHand(currentHand: List~NonStarterCard~)
        + getCurrentHand() List~NonStarterCard~
        + getSecretObjetive() ObjectiveCard
        + getConnectionType() boolean
        + getInterfaceType() boolean
    }
    %%Player --> NonStarterCard
    %%Player --> TokenColor
    %%Player --> ObjectiveCard
    class ScoreTrackBoard {
        - playersScore: Map~String, Integer~
        + ScoreTrackBoard()
        + addPlayer(nickname: String)
        + setScore(nickname: String, newScore: int)
        + getScore(nickname: String) int
        + incrementScore(nickname: String, deltaScore: int)
    }
    %%ScoreTrackBoard --> Player




