classDiagram
    %% -----------------------------
    %% Network
    %% -----------------------------

    %% -----------------------------
    %% Rmi
    %% -----------------------------

    ChatListener <|-- VirtualView
    GameFieldListener <|-- VirtualView
    GameListener <|-- VirtualView
    PlayerListener <|-- VirtualView
    ScoreTrackBoardListener <|-- VirtualView
    DeckListener <|-- VirtualView


    VirtualView <|-- RmiClient
    VirtualView  <-- SocketClientHandler

    VirtualServerGame <|-- RmiServerGame
    VirtualServerGame <|-- VirtualSocketServer

    VirtualServerGamesManager <|-- RmiServerGamesManager
    VirtualServerGamesManager <|-- VirtualSocketServer

    class RmiClient{
        - nickname: String
        - serverGamesManager: VirtualServerGamesManager
        - serverGame: VirtualServerGame
        - gameView: GameView
        + RmiClient(nickname: String,serverGamesManager: VirtualServerGamesManager)
        + connectToGamesManagerServer(connectionType: boolean,interdaceType: boolean)
        + reconnectPlayer(nickname: String,connectionType: boolean,interdaceType: boolean)
        + setServerGame(serverGame: VirtualServerGame)
        - connectToGameServer()
        + notifyJoinNotSuccessful()
        + getNickname() String
        + startGamesManagerPing()
        + startGamePing()
        + runCliJoinGame()
        + runCliGame()
        + receiveChatMessageUpdate(chatMessageUpdate: ChatMessageUpdate)
        + receiveStarterCardUpdate(starterCardUpdate: StarterCardUpdate)
        + receivePlacedCardUpdate(placedCardUpdate: PlacedCardUpdate)
        + receiveGameModelUpdate(gameModelUpdate: GameModelUpdate)
        + receivePlayerJoinedUpdate(playerJoinedUpdate: PlayerJoinedUpdate)
        + receiveCommandResultUpdate(commandResultUpdate: CommandResultUpdate)
        + receiveStallUpdate(stallUpdate: StallUpdate)
        + receiveConnectionUpdate(connectionUpdate: ConnectionUpdate)
        + receiveCardHandUpdate(cardHandUpdate: CardHandUpdate)
        + receiveScoreUpdate(scoreUpdate: ScoreUpdate)
        + receiveExistingGamesUpdate(existingGamesUpdate: ExistingGamesUpdate)
        + receiveDeckUpdate(deckUpdate: DeckUpdate)
    }
    class RmiServerGame{
        - gameController: GameController
        - commandsQueue: BlockingDeque~GameCommand~
        + RmiServerGame(gameController: GameController)
        - startCommandExecutor()
        + connect(client: VirtualView)
        + setAndExecuteCommand(gameControllerCommand: GameCommand)
    }
    class RmiServerGamesManager{
        - myRmiServerGamesManager: RmiServerGamesManager
        - clients: List~VirtualView~
        - rmiServerGames: Map~Integer, RmiServerGame~
        - commandsQueue: BlockingDeque~GamesManagerCommand~
        - RmiServerGamesManager()
        + getRmiServerGamesManager() RmiServerGamesManager
        - startCommandExecutor()
        + connect(client: VirtualView)
        + checkNickname(nickname: String) NicknameCheck
        + setAndExecuteCommand(gamesManagerCommand: GamesManagerCommand)
        + setServerGame(nickname: String, gameId: int)
        + createServerGame(nickname: String, gameId: int)
        + notifyJoinNotSuccessful(nickname: String)
        + displayGames(nickname: String)
        + getVirtualView(nickname: String) VirtualView
        + deleteGame(gameId: int)
        + removeVirtualView(nickname: String)
    }
    %% -----------------------------
    %% Socket
    %% -----------------------------
    class SocketClient{
        - nickname: String
        - mySocket: Socket
        - gameView: GameView
        - input: ObjectInputStream
        - myServer: VirtualSocketServer
        + SocketClient(nickname: String, mySocket: Socket)
        - run()
        + connectToGamesManager(connectionType: boolean, interfaceType: boolean)
        - manageReceivedMessage()
        + runCliJoinGame()
        - runCliGame()
    }
    class SocketClientHandler{
        - gamesManager: GamesManager
        - gameController: GameController
        - mySocket: Socket
        - input: ObjectInputStream
        - output: ObjectOutputStream
        + SocketClientHandler(gamesManager: GamesManager, gameController: GameController)
        - manageGamesManagerCommand()
        - manageGameCommand()
        + closeConnection(mySocket: Socket, input: ObjectInputStream, output: ObjectOutputStream)
        + setServerGame(serverGame: VirtualServerGame)
        + getNickname() String
        - receiveUpdate(update: Update)
        + receiveChatMessageUpdate(chatMessageUpdate: ChatMessageUpdate)
        + receiveDeckUpdate(deckUpdate: DeckUpdate)
        + receiveStarterCardUpdate(starterCardUpdate: StarterCardUpdate)
        + receivePlacedCardUpdate(placedCardUpdate: PlacedCardUpdate)
        + receiveGameModelUpdate(gameModelUpdate: GameModelUpdate)
        + receivePlayerJoinedUpdate(playerJoinedUpdate: PlayerJoinedUpdate)
        + receiveCommandResultUpdate(commandResultUpdate: CommandResultUpdate)
        + receiveStallUpdate(stallUpdate: StallUpdate)
        + receiveConnectionUpdate(connectionUpdate: ConnectionUpdate)
        + receiveCardHandUpdate(cardHandUpdate: CardHandUpdate)
        + receiveScoreUpdate(scoreUpdate: ScoreUpdate)
        + receiveExistingGamesUpdate(existingGamesUpdate: ExistingGamesUpdate)
        + notifyJoinNotSuccessful()
    }
    class SocketServer{
        - mySocket: ServerSocket
        - clients: List~SocketClientHandler~
        + SocketServer(mySocket: ServerSocket)
        + runServer()
    }
    class VirtualSocketServer{
        - output: ObjectOutputStream
        + VirtualSocketServer(output: ObjectOutputStream)
        + setAndExecuteCommand(gameControllerCommand: GameCommand)
        + setAndExecuteCommand(gamesManagerCommand: GamesManagerCommand)
        + checkNickname(nickname: String)
    }

    class PingReceiver{
        - gameController: GameController
        - playersPing: Map~String,Boolean~
        - maxMissedPings: int
        + PingReceiver(gameController: GameController)
        + addPlayer(nickname: String)
        + receivePing(nickname: String)
        + checkPing(nickname: String)
    }
    class PingSender{
        <<interface>>
        ~ startGamePing()
        ~ startGamesManagerPing()
    }
    class VirtualServerGame{
        <<interface>>
        ~ connect(client: VirtualView)
        ~ setAndExecuteCommand(gameControllerCommand: GameCommand)
    }
    class VirtualServerGamesManager{
        <<interface>>
        ~ connect(client: VirtualView)
        ~ checkNickname(nickname: String) NicknameCheck
        ~ setAndExecuteCommand(gamesManagerCommand: GamesManagerCommand)
    }
    class VirtualView{
        <<interface>>
        ~ getNickname() String
        ~ setServerGame(serverGame: VirtualServerGame)
        ~ receiveExistingGamesUpdate(existingGamesUpdate: ExistingGamesUpdate)
        ~ notifyJoinNotSuccessful()
    }

    %% -----------------------------
    %% Listeners
    %% -----------------------------

    class ChatListener {
        <<interface>>
        ~ receiveChatMessageUpdate(chatMessageUpdate: ChatMessageUpdate)
    }
    class DeckListener {
        <<interface>>
        ~ receiveStarterCardUpdate(starterCardUpdate StarterCardUpdate)
        ~ receivePlacedCardUpdate(placedCardUpdate PlacedCardUpdate)
    }
    class GameFieldListener{
        <<interface>>
        ~ receiveStarterCardUpdate(starterCardUpdate StarterCardUpdate)
        ~ receivePlacedCardUpdate(placedCardUpdate PlacedCardUpdate)
    }
    class GameListener{
        <<interface>>
        ~ receiveGameModelUpdate(gameModelUpdate GameModelUpdate)
        ~ receivePlayerJoinedUpdate(playerJoinedUpdate PlayerJoinedUpdate)
        ~ receiveCommandResultUpdate(commandResultUpdate CommandResultUpdate)
    }
    class PlayerListener {
        <<interface>>
        ~ receiveStallUpdate(stallUpdate StallUpdate)
        ~ receiveConnectionUpdate(connectionUpdate ConnectionUpdate)
        ~ receiveCardHandUpdate(cardHandUpdate CardHandUpdate)
    }
    class ScoreTrackBoardListener {
        <<interface>>
        ~ receiveScoreUpdate(scoreUpdate ScoreUpdate)
    }